version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: root
      POSTGRES_DB: root
    # volumes:
      # - timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - grafana_network
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: timescaledb
      GF_DATABASE_PORT: 5432
      GF_DATABASE_NAME: root
      GF_DATABASE_USER: root
      GF_DATABASE_PASSWORD: toor
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    restart: always
    networks:
      - grafana_network
networks:
  grafana_network:
# volumes:
#   timescaledb_data:
